import os
import glob
import re
import json

WORKSPACE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
EN_DIR = os.path.join(WORKSPACE, "en")

# 1. Load existing dictionary
dict_file = os.path.join(WORKSPACE, "cms_system", "cms_data", "en_dictionary.json")
with open(dict_file, "r", encoding="utf-8") as f:
    en_dict = json.load(f)

# 2. Comprehensive translations for all remaining phrases found in all_remaining_chinese_words.json
EXHAUSTIVE_PAIRS = [
    # Forms & Feedback
    ('value="提 交"', 'value="Submit"'),
    ('value="提交"', 'value="Submit"'),
    ("提 交", "Submit"),
    ("提交", "Submit"),
    ("请真实详尽填写Message Content", "Please provide detailed message content"),
    ("请真实详尽填写", "Please provide detailed "),
    ("请填写您的电子邮件, 填写后我司将通过电子邮件给您回复", "Please enter your email; our team will reply via email"),
    ("填写后我司将通过电子邮件给您回复", "our team will respond via email"),
    ("请填写您的手机号码, After submission, ", "Please enter your mobile phone number. After submission, "),
    ("请填写您的手机号码", "Please enter your mobile phone number"),
    ("请填写Your Name, 以便于我方给您回复", "Please enter your name for follow-up communication"),
    ("以便于我方给您回复", "for our team to reply"),
    ("请填写", "Please enter "),
    ("留下您的联系方式, 我们的销售推广人员将在2小时内回复您", "Leave your contact details; our technical sales representatives will respond within 2 hours"),
    ("我们的销售推广人员将在2小时内回复您", "our technical sales team will reply within 2 hours"),
    ("小时内回复您", "hours"),
    ("留下您的联系方式", "Leave your contact details"),
    ("若有需求或其他反馈, 可留言Mellgen Biotech,Mell", "For inquiries or feedback, please contact Mellgen Biotech, "),
    ("若有需求或其他反馈, 可留言Mellgen Biotech", "For inquiries or feedback, please contact Mellgen Biotech"),
    ("若有需求或其他反馈", "For inquiries or feedback"),
    ("可留言Mellgen Biotech", "contact Mellgen Biotech"),
    ("留言Mellgen Biotech", "Contact Mellgen Biotech"),
    ("留言", "Inquire"),
    ("尊敬的访客", "Dear Visitor"),
    ("公司地址", "Company Address"),
    ("欢迎通过以下几种方式Contact Us:", "Welcome to contact us through the following channels:"),
    ("欢迎通过以下几种方式", "Welcome to contact us through:"),
    ("如有需要Cosmetic Raw Materials", "If you need cosmetic raw materials"),
    ("如有需要", "If you require "),
    ("如有需求, 可拨打Mellgen Biotech联系方式", "For inquiries, please call Mellgen Biotech"),
    ("如有需求", "For inquiries"),
    ("可拨打", "please call "),
    ("联系方式:0755-82926499", "Contact: +86-755-82926499"),
    ("联系方式", "Contact Information"),
    ("联系", "Contact"),
    ("姓名: ", "Name: "),
    ("姓名", "Name"),
    ("手机号码: ", "Mobile Phone: "),
    ("手机号码", "Mobile Phone"),
    ("电子邮件: ", "Email Address: "),
    ("电子邮件", "Email Address"),
    ("需求沟通", "Requirements Discussion"),
    ("科学家团队", "Scientist Team"),
    ("品牌方", "Brand Partners"),
    ("邮箱", "Email"),
    ("地址", "Address"),
    ("返回顶部", "Back to Top"),
    ("返回Product Center", "Back to Product Center"),
    ("返回", "Back to "),
    ("XML地图", "XML Sitemap"),
    ("地图", "Sitemap"),
    ("分类", "Categories"),
    ("免费获取Services", "Request Free Services"),
    ("免费获取", "Request Free "),
    ("原料产品", "Raw Material Products"),

    # Article / News Titles & Snippets
    ("突破透皮困局! 中国团队发现PDRN抗老新靶点, Mellgen Biotech Cyclic Peptide...",
     "Breaking Transdermal Limits! Chinese Team Discovers PDRN Anti-Aging Target, Mellgen Cyclic Peptide..."),
    ("突破透皮困局! 中国团队发现PDRN抗老新靶点, M",
     "Breaking Transdermal Limits! Chinese Team Discovers PDRN Anti-Aging Target, Mellgen..."),
    ("突破透皮困局! 中国团队发现PDRN抗老新靶点",
     "Breaking Transdermal Limits! Chinese Team Discovers PDRN Anti-Aging Target"),
    ("突破透皮困局", "Breaking Transdermal Limits"),
    ("中国团队发现", "Chinese Team Discovers "),
    ("抗老新靶点", "Anti-Aging Target"),
    ("cTDP以 \"钥匙-锁\"精准机制 , 开启颠覆性透皮革命:",
     "cTDP utilizes a 'Key-Lock' precision mechanism to unlock a disruptive transdermal revolution:"),
    ("cTDP以 \"钥匙-锁\"精准机制", "cTDP utilizes a 'Key-Lock' precision mechanism"),
    ("\"钥匙-锁\"精准机制", "'Key-Lock' precision mechanism"),
    ("精准机制", "precision mechanism"),
    ("钥匙", "Key"),
    ("锁", "Lock"),
    ("开启颠覆性透皮革命:", "unlocking a disruptive transdermal revolution:"),
    ("开启颠覆性透皮革命", "unlocking a disruptive transdermal revolution"),
    ("美尔健生物「Transdermal Cyclic Peptide」cTDP, 站on 'Great Chinese Raw Materials'总决赛舞台!",
     "Mellgen Biotech's 'Transdermal Cyclic Peptide' cTDP stands on the grand finals stage of 'Great Chinese Raw Materials'!"),
    ("美尔健生物「Transdermal Cyclic Peptide」", "Mellgen Biotech's 'Transdermal Cyclic Peptide' "),
    ("美尔健生物", "Mellgen Biotech"),
    ("美尔", "Mell"),
    ("健生物", "gen Biotech"),
    ("总决赛舞台!", "Grand Finals Stage!"),
    ("总决赛舞台", "Grand Finals Stage"),
    ("站on", "standing on "),
    ("站", "standing "),
    ("10倍+ Enhances Collagen", "10x+ Enhances Collagen"),
    ("10倍+", "10x+ "),
    ("Mellgen Biotech打造的\"肌肤之钥\", ", "Mellgen Biotech's 'Key to Skin Radiance', "),
    ("Mellgen Biotech打造的\"肌肤之钥\"", "Mellgen Biotech's 'Key to Skin Radiance'"),
    ("打造的", "crafted "),
    ("肌肤之钥", "Key to Skin Radiance"),
    ("未来美妆战场, 创新定......", "Future Beauty Battlefield: Innovation Defines Market Leadership..."),
    ("未来美妆战场, 创新定", "Future Beauty Battlefield: Innovation Defines Market Leadership"),
    ("未来美妆战场", "Future Beauty Battlefield"),
    ("创新定", "Innovation Defines"),
    ("皮肤护理做不好? 这里......", "Skin Care Ineffective? Find the Scientific Solution Here..."),
    ("皮肤护理做不好? 这里", "Skin Care Ineffective? Find the Scientific Solution Here"),
    ("皮肤护理做不好", "Skin Care Ineffective"),
    ("这里", "Here"),
    ("你还在用没效果的护肤......", "Still Using Ineffective Skincare?..."),
    ("你还在用没效果的护肤", "Still Using Ineffective Skincare"),
    ("2025护肤品市场千......", "2025 Skincare Market Trends..."),
    ("2025护肤品市场千", "2025 Skincare Market Trends"),
    ("\"中国芯\"原料定制, ......", "'Core Biotech' Raw Material Customization..."),
    ("\"中国芯\"原料定制, ", "'Core Biotech' Raw Material Customization"),
    ("\"中国芯\"原料定制", "'Core Biotech' Raw Material Customization"),
    ("\"中国芯\"", "'Core Biotech'"),
    ("原料定制", "Raw Material Customization"),
    ("一把钥匙, 打开六大护理结界; 一...", "One key unlocking six skincare barriers..."),
    ("一把钥匙, 打开六大护理结界", "One key unlocking six skincare barriers"),
    ("一把钥匙", "One Key"),
    ("打开六大护理结界", "Unlocking Six Skincare Barriers"),
    ("登《Nature》、拿专利、斩...", "Published in Nature, Granted Patents, Winning Awards..."),
    ("登《Nature》、拿专利、斩", "Published in Nature, Granted Patents, Winning Awards"),
    ("登《Nature》", "Published in Nature"),
    ("拿专利", "Granted Patents"),
    ("斩", "Winning Awards"),
    ("细胞\"Power Bank Arrives! Energy Cyclic Peptide EAC: Fully Recharge Your Skin",
     "Cellular 'Power Bank' Arrives! Energy Cyclic Peptide EAC: Fully Recharge Your Skin"),
    ("细胞\"充电宝\"来了! 聚能Cyclic PeptideE...",
     "Cellular 'Power Bank' Arrives! Energy Cyclic Peptide EAC..."),
    ("细胞\"充电宝\"来了! 聚能Cyclic PeptideE",
     "Cellular 'Power Bank' Arrives! Energy Cyclic Peptide EAC"),
    ("细胞\"充电宝\"来了!", "Cellular 'Power Bank' Arrives!"),
    ("充电宝", "Power Bank"),
    ("来了", "Arrives"),
    ("聚能", "Energy Accumulation"),
    ("Mellgen Biotech: 以科学之钥, 解锁胶...", "Mellgen Biotech: Unlocking Collagen Science with the Key of Innovation..."),
    ("Mellgen Biotech: 以科学之钥, 解锁胶", "Mellgen Biotech: Unlocking Collagen Science with the Key of Innovation"),
    ("以科学之钥, 解锁胶", "Unlocking Collagen Science with the Key of Innovation"),
    ("以科学之钥", "With the Key of Science"),
    ("解锁胶", "Unlocking Collagen"),
    ("解锁300+功效活性Ingredients的透皮革命", "Unlocking the Transdermal Revolution for 300+ Efficacy Bio-Actives"),
    ("300+功效活性Ingredients的透皮革命", "Transdermal Revolution for 300+ Efficacy Bio-Actives"),
    ("功效活性Ingredients的透皮革命", "Transdermal Revolution for Efficacy Bio-Actives"),
    ("功效活性", "Efficacy Bio-Actives"),
    ("的透皮革命", "Transdermal Revolution"),
    ("解锁", "Unlocking "),
    ("十大创新原料奖", "Top 10 Innovative Raw Materials Award"),
    ("中国科技创新发明成果", "China Sci-Tech Innovation Invention Award"),
    ("happi国际个人护理品", "happi International Personal Care"),
    ("国际个人护理品", "International Personal Care"),
    ("原料质量奖", "Raw Material Quality Award"),
    ("Invention Patents墙", "Invention Patents Wall"),
    ("墙", " Wall"),
    ("从原料到配方, Mellgen Biotech为200+brands with one-",
     "From Ingredients to Formulations, Mellgen Biotech Empowers 200+ Brands with One-Stop Solutions"),
    ("从原料到配方, Mellgen Biotech为",
     "From Ingredients to Formulations, Mellgen Biotech Empowers "),
    ("从原料到配方", "From Ingredients to Formulations"),
    ("到配方", "to Formulations"),
    ("肽维多", "Peptivida"),
    ("皮肤修复\"隐形大佬\": Fibronectin, 为何99%的人还不知道?",
     "Skin Repair's Hidden Giant: Fibronectin - Why Do 99% of People Still Not Know?"),
    ("皮肤修复\"隐形大佬\": Fibronectin, 为何99%的人还不知道",
     "Skin Repair's Hidden Giant: Fibronectin - Why Do 99% of People Still Not Know"),
    ("隐形大佬\": Fibronectin, 为何99%的人还不知道",
     "Hidden Giant: Fibronectin - Why Do 99% of People Still Not Know"),
    ("隐形大佬", "Hidden Giant"),
    ("为何99%的人还不知道", "Why Do 99% of People Still Not Know"),
    ("为何", "Why "),
    ("的人还不知道", " Still Do Not Know"),
    ("获中国Invention Patents授权, Leading High Penetration Era",
     "Granted Chinese Invention Patent, Leading High Penetration Era"),
    ("获中国Invention Patents授权", "Granted Chinese Invention Patent"),
    ("获中国", "Granted Chinese "),
    ("授权", "Authorization"),
    ("高效渗透新时代!", "High Penetration New Era!"),
    ("高效渗透新时代", "High Penetration New Era"),
    ("【专利创新】Marine Brightening FactorInvention Patents获批! 见证\"透光肌\"养成奇迹",
     "[Patent Innovation] Marine Brightening Factor Invention Patent Approved! Witness the Miracle of Translucent Skin"),
    ("【专利创新】Marine Brightening FactorInvention Patents获批!",
     "[Patent Innovation] Marine Brightening Factor Invention Patent Approved!"),
    ("见证&quot;透光肌&quot;养成奇迹", "Witness the Miracle of Translucent Skin"),
    ("见证\"透光肌\"养成奇迹", "Witness the Miracle of Translucent Skin"),
    ("透光肌", "Translucent Skin"),
    ("养成奇迹", "Cultivation Miracle"),
    ("见证", "Witness "),
    ("获批", "Approved"),
    ("专利创新", "Patent Innovation"),
    ("焕活肌肤新生力! Mellgen BiotechTransdermal Fibronectin, 科学修复敏感肌",
     "Revitalizing Skin Renewal! Mellgen Transdermal Fibronectin: Scientifically Repairing Sensitive Skin"),
    ("焕活肌肤新生力", "Revitalizing Skin Renewal"),
    ("科学修复敏感肌", "Scientifically Repairing Sensitive Skin"),
    ("Transdermal Cyclic Peptide-讲解", "Transdermal Cyclic Peptide - Presentation"),
    ("讲解", "Presentation"),
    ("人源重组Ⅲ型胶原", "Recombinant Human Type III Collagen"),
    ("人源重组", "Recombinant Human "),
    ("型胶原", "Type Collagen"),
    ("水母多糖", "Jellyfish Polysaccharide"),
    ("次世代Collagen. 低风险, 易提取, 高活性, 低限制, 应用广INCI:",
     "Next-Gen Collagen: Low risk, high yield, high bioactivity, minimal constraints, broad utility. INCI:"),
    ("次世代Collagen", "Next-Generation Collagen"),
    ("次世代", "Next-Generation "),
    ("低风险, 易提取, 高活性, 低限制, 应用广",
     "Low risk, easy extraction, high bioactivity, minimal constraints, broad formulation utility"),
    ("低风险", "Low risk"),
    ("易提取", "easy extraction"),
    ("高活性", "high bioactivity"),
    ("低限制", "minimal constraints"),
    ("应用广", "broad formulation utility"),
    ("一种来自10亿年前的生物材料低风险、易提取、High Purity、应用广",
     "A 1-billion-year-old biomaterial: Low risk, easy extraction, high purity, broad utility"),
    ("一种来自10亿年前的生物材料", "A biomaterial originating from 1 billion years ago"),
    ("10亿年前的生物材料", "1-billion-year-old biomaterial"),
    ("一种来自", "A material from "),
    ("亿年前的生物材料低风险", "1-billion-year-old biomaterial, low risk"),
    ("Mussel adhesive protein forms a protective barrier on the skin surface, 起到物理屏障作用, 这可能是其...",
     "Mussel adhesive protein forms a protective barrier on the skin surface, shielding sensitive skin..."),
    ("起到物理屏障作用, 这可能是其", "providing a physical shield that underpins its protective properties"),
    ("起到物理屏障作用", "providing a physical shield"),
    ("这可能是其", "which underpins its "),
    ("结合皮肤微生态, 提取云南高山桃胶, 酶技术多糖小分子化...",
     "Integrating skin microbiome science, extracting Yunnan alpine peach gum with enzymatic micro-polysaccharide technology..."),
    ("结合皮肤微生态, 提取云南高山桃胶, 酶技术多糖小分子化",
     "Integrating skin microbiome science, extracting Yunnan alpine peach gum with enzymatic micro-polysaccharide technology"),
    ("结合皮肤微生态", "Integrating skin microbiome science"),
    ("提取云南高山桃胶", "extracting Yunnan alpine peach gum"),
    ("酶技术多糖小分子化", "enzymatic micro-polysaccharide technology"),
    ("MELLPRO3Dcollagen3D胶原是一种含有Ⅰ,Ⅲ,Ⅳ型...",
     "MELLPRO 3D Collagen is a full-spectrum collagen complex containing Type I, III, and IV collagens..."),
    ("3D胶原是一种含有Ⅰ,Ⅲ,Ⅳ型", "3D Collagen is a full-spectrum collagen complex containing Type I, III, and IV collagens"),
    ("胶原是一种含有", "Collagen is a complex containing "),
    ("USAFDACGMP认证细胞级修复, 真皮层...",
     "US FDA cGMP certified cellular repair, dermal regeneration..."),
    ("认证细胞级修复, 真皮层", "certified cellular repair, dermal regeneration"),
    ("认证细胞级修复", "certified cellular repair"),
    ("真皮层", "dermal layer"),
    ("来自海洋的蓝精灵, 美白, 亮肤, 抗氧化, 应有尽有INCI:氧化还原...",
     "Marine Blue Sprite: Whitening, brightening, antioxidant all-in-one. INCI: Oxidoreductase..."),
    ("来自海洋的蓝精灵, 美白, 亮肤, 抗氧化, 应有尽有",
     "Marine Blue Sprite: Whitening, brightening, antioxidant all-in-one"),
    ("来自海洋的蓝精灵", "Marine Blue Sprite"),
    ("美白, 亮肤, 抗氧化, 应有尽有", "Whitening, brightening, antioxidant all-in-one"),
    ("美白", "Whitening"),
    ("亮肤", "Brightening"),
    ("抗氧化", "Antioxidant"),
    ("应有尽有", "All-in-One"),
    ("氧化还原", "Oxidoreductase"),
    ("Marine psychrophilic lysozyme is an enzyme discovered from marine bacteriophages, 是胞壁质酶或N-...",
     "Marine psychrophilic lysozyme is an enzyme discovered from marine bacteriophages, functioning as a muramidase or N-acetylmuramidase..."),
    ("是胞壁质酶或N-", "functioning as a muramidase or N-acetylmuramidase"),
    ("是胞壁质酶或", "functioning as a muramidase or "),
    ("MEGCALMGPT——取自长白山黑灵芝、人参根以及野生松茸, 经...",
     "MEGCALMGPT: Sourced from Changbai Mountain black reishi, ginseng root, and wild matsutake, through..."),
    ("取自长白山黑灵芝、人参根以及野生松茸",
     "Sourced from Changbai Mountain black reishi, ginseng root, and wild matsutake"),
    ("取自长白山黑灵芝", "Sourced from Changbai Mountain black reishi"),
    ("人参根以及野生松茸", "ginseng root, and wild matsutake"),
    ("经...", "through advanced extraction..."),
    ("自然之美, 科技之光, 全球一款基于生物仿生技术, 促细胞生长, 透皮信...",
     "Beauty of nature and light of science: First globally biomimetic peptide promoting cellular proliferation, transdermal signaling..."),
    ("自然之美, 科技之光, 全球一款基于生物仿生技术, 促细胞生长",
     "Beauty of nature and light of science: First globally biomimetic peptide promoting cellular proliferation"),
    ("自然之美, 科技之光", "Beauty of nature and light of science"),
    ("全球一款基于生物仿生技术", "First globally biomimetic peptide"),
    ("促细胞生长", "promoting cellular proliferation"),
    ("透皮信", "transdermal signaling"),
    ("肌底的营养盛宴, 科学配伍, 为皮肤提供丰富营养素. INCI: 生物素...",
     "Skin Nutrition Feast: Scientifically blended to provide rich nourishment. INCI: Biotin..."),
    ("肌肤的营养盛宴, 科学配伍, 为皮肤提供丰富营养素. INCI: 生物素...",
     "Skin Nutrition Feast: Scientifically blended to provide rich nourishment. INCI: Biotin..."),
    ("肌肤的营养盛宴, 科学配伍, 为皮肤提供丰富营养素.",
     "Skin Nutrition Feast: Scientifically blended to provide rich nourishment."),
    ("肌肤的营养盛宴", "Skin Nutrition Feast"),
    ("科学配伍", "Scientifically blended"),
    ("为皮肤提供丰富营养素", "providing rich nourishment for skin"),
    ("生物素", "Biotin"),
    ("透皮科技新突破, 高效促渗重构活性Ingredients应用价值",
     "Transdermal Tech Breakthrough: High-Efficiency Penetration Reinvents Bio-Active Value"),
    ("高效促渗重构活性Ingredients应用价值", "High-Efficiency Penetration Reinvents Bio-Active Value"),
    ("透皮科技新突破", "Transdermal Tech Breakthrough"),
    ("高效促渗重构活性", "High-Efficiency Penetration Reinvents Bio-Actives"),
    ("应用价值", "Application Value"),
    ("亿级智造赋能, 定制您的美妆基因", "Multi-Million Intelligent Manufacturing Empowering Custom Beauty DNA"),
    ("亿级智造赋能", "Multi-Million Intelligent Manufacturing"),
    ("定制您的美妆基因", "Empowering Custom Beauty DNA"),
    ("以超分子自组装技术打破僵局, 将Transdermal Cyclic Peptide与...",
     "Breaking bottlenecks via supramolecular self-assembly, integrating Transdermal Cyclic Peptides with bio-actives..."),
    ("以超分子自组装技术打破僵局, 将Transdermal Cyclic Peptide与",
     "Breaking bottlenecks via supramolecular self-assembly, integrating Transdermal Cyclic Peptides with "),
    ("以超分子自组装技术打破僵局", "Breaking bottlenecks via supramolecular self-assembly"),
    ("采用自主研发的科学配方, 精选了Transdermal Fibronectin、Collagen等多种Ingredients, 与人...",
     "Formulated with proprietary science, combining Transdermal Fibronectin, Collagen, and skin-compatible bio-actives..."),
    ("采用自主研发的科学配方, 精选了", "Formulated with proprietary science, combining "),
    ("采用自主研发的科学配方", "Formulated with proprietary science"),
    ("精选了", "selecting "),
    ("等多种Ingredients, 与人...", " and multiple bio-actives biocompatible with human skin..."),
    ("等多种Ingredients, 与人", " and multiple bio-actives biocompatible with human skin"),
    ("等多种", " and other "),
    ("与人", "biocompatible with human "),
    ("含有丰富的氨基酸, 水解Proteins酶、还原酶以及小分子多肽等物质. 能够激...",
     "Rich in amino acids, proteolytic enzymes, reductases, and oligopeptides, activating cellular renewal..."),
    ("含有丰富的氨基酸, 水解Proteins酶、还原酶以及小分子多肽等物质.",
     "Rich in amino acids, proteolytic enzymes, reductases, and oligopeptides."),
    ("含有丰富的氨基酸", "Rich in amino acids"),
    ("还原酶以及小分子多肽等物质. 能够激...", "reductases, and oligopeptides, activating renewal..."),
    ("还原酶以及小分子多肽等物质", "reductases, and oligopeptides"),
    ("水解Proteins酶", "proteolytic enzymes"),
    ("水解", "hydrolyzed "),
    ("能够激", "activating "),
    ("是以钠钾ATP酶β-亚基作为筛选靶...<a", "Screened using the sodium-potassium ATPase beta-subunit as a target...<a"),
    ("是以钠钾ATP酶β-亚基作为筛选靶", "Screened using the sodium-potassium ATPase beta-subunit as a target"),
    ("是以钠钾", "Screened using Na+/K+ "),
    ("亚基作为筛选靶", "beta-subunit as screening target"),
    ("ATP酶", "ATPase"),
    ("环磷酸腺苷", "Cyclic AMP"),
    ("Water Soluble解性:Water Soluble", "Solubility: Water Soluble"),
    ("Water Soluble解性", "Solubility"),
    ("Water Soluble性胶原", "Soluble Collagen"),
    ("Soluble性胶原", "Soluble Collagen"),
    ("性胶原", "Soluble Collagen"),
    ("重组CollagenProteins溶液", "Recombinant Collagen Solution"),
    ("重组CollagenProteins原液", "Recombinant Collagen Solution"),
    ("重组CollagenProteins", "Recombinant Collagen"),
    ("CollagenProteins溶液", "Collagen Solution"),
    ("CollagenProteins原液", "Collagen Solution"),
    ("CollagenProteins", "Collagen"),
    ("重组", "Recombinant "),
    ("溶液", "Solution"),
    ("原液", "Solution"),
    ("水母Collagen", "Jellyfish Collagen"),
    ("水母", "Jellyfish "),

    # Website Navigation & Section Banners
    ("Mellgen网站Home", "Mellgen Website Home"),
    ("Mellgen资讯频道", "Mellgen News & Insights"),
    ("Mellgen公司信息", "Mellgen Corporate Information"),
    ("网站Home", "Website Home"),
    ("资讯频道", "News & Insights"),
    ("公司信息", "Corporate Information"),
    ("网站", "Website"),
    ("温 and 舒缓干痒不适! 这款「Probiotic Soothing Factor」敏感肌终于有救了",
     "Gentle & Soothing for Dry Itchy Skin! Probiotic Soothing Factor: Ultimate Relief for Sensitive Skin"),
    ("温 and 舒缓干痒不适!", "Gentle & Soothing for Dry Itchy Skin!"),
    ("舒缓干痒不适", "Soothing Dry Itchy Skin"),
    ("这款「Probiotic Soothing Factor」敏感肌终于有救了", "Probiotic Soothing Factor: Ultimate Relief for Sensitive Skin"),
    ("这款", "This "),
    ("敏感肌终于有救了", "Ultimate Relief for Sensitive Skin"),
    ("AI + 透皮技术双轮驱动: Mellgen重塑护肤品研发新范式",
     "Dual Drivers of AI + Transdermal Delivery: Mellgen Reshapes Skincare R&D Paradigms"),
    ("透皮技术双轮驱动", "Dual Drivers of Transdermal Tech"),
    ("重塑护肤品研发新范式", "Reshaping Skincare R&D Paradigms"),
    ("创新Transdermal Cyclic Peptide cTDP, 开启高效护肤的\"吸收密钥\"",
     "Innovative Transdermal Cyclic Peptide cTDP: Unlocking the Absorption Key for Efficacy Skincare"),
    ("开启高效护肤的\"吸收密钥\"", "Unlocking the Absorption Key for Efficacy Skincare"),
    ("开启高效护肤的", "Unlocking High-Efficiency Skincare's "),
    ("吸收密钥", "Absorption Key"),
    ("Proteins才是肌肤 \"小弹簧\"? Mellgen透皮科技让弹润不费力!",
     "Proteins as the Skin's 'Spring Mattress'? Mellgen Transdermal Tech Delivers Effortless Elasticity!"),
    ("Proteins才是肌肤 \"小弹簧\"?", "Proteins as the Skin's 'Spring Mattress'?"),
    ("才是肌肤", "as the Skin's "),
    ("小弹簧", "Spring Mattress"),
    ("透皮科技让弹润不费力!", "Mellgen Transdermal Tech Delivers Effortless Elasticity!"),
    ("透皮科技让弹润不费力", "Mellgen Transdermal Tech Delivers Effortless Elasticity"),
    ("Proteins护肤新革命! Mellgen透皮技术让活性Ingredients \"钻\" 进肌底✨",
     "Protein Skincare Revolution! Mellgen Transdermal Tech Drives Bio-Actives Deep into the Dermis ✨"),
    ("Proteins护肤新革命!", "Protein Skincare Revolution!"),
    ("护肤新革命", "Skincare Revolution"),
    ("透皮技术让活性Ingredients \"钻\" 进肌底✨", "Transdermal Tech Drives Bio-Actives Deep into the Dermis ✨"),
    ("透皮技术让活性Ingredients \"钻\" 进肌底", "Transdermal Tech Drives Bio-Actives Deep into the Dermis"),
    ("透皮技术让活性", "Transdermal Tech Drives Bio-Actives "),
    ("\"钻\" 进肌底✨", "Deep into the Dermis ✨"),
    ("\"钻\" 进肌底", "Deep into the Dermis"),
    ("钻", "Penetrate"),
    ("进肌底", "into the Dermis"),
    ("PDRN深层修护新纪元: Mellgen BiotechPDRN Cyclic Peptide Stick开启高阶紧致修护新时代",
     "A New Era of Deep PDRN Repair: Mellgen PDRN Cyclic Peptide Stick Unlocks Advanced Firming & Renewal"),
    ("PDRN深层修护新纪元", "A New Era of Deep PDRN Repair"),
    ("深层修护新纪元", "A New Era of Deep Repair"),
    ("开启高阶紧致修护新时代", "Unlocking Advanced Firming & Renewal Era"),
    ("告别EGF争议! 这款蜗牛胶原, 安全与功效我全都要",
     "Moving Beyond EGF Controversies: Snail Collagen Delivers Both Safety and Proven Efficacy"),
    ("告别EGF争议!", "Moving Beyond EGF Controversies!"),
    ("告别", "Moving Beyond "),
    ("争议", "Controversies"),
    ("这款蜗牛胶原, 安全与功效我全都要", "Snail Collagen Delivers Both Safety and Proven Efficacy"),
    ("这款蜗牛胶原", "This Snail Collagen"),
    ("安全与功效我全都要", "Delivering Both Safety and Proven Efficacy"),
    ("核心科技: 开启高效吸收新纪元——Mellgen BiotechTransdermal Fibronectin",
     "Core Technology: Pioneering the High-Absorption Era - Mellgen Transdermal Fibronectin"),
    ("开启高效吸收新纪元", "Pioneering the High-Absorption Era"),
    ("聚焦 PCHI2026! Mellgen Biotech以Transdermal Tech引领国货原料新征程",
     "Spotlight on PCHi 2026! Mellgen Leads Domestic Ingredients Frontier via Transdermal Delivery"),
    ("聚焦 PCHI2026!", "Spotlight on PCHi 2026!"),
    ("聚焦", "Spotlight on "),
    ("以Transdermal Tech引领国货原料新征程", "Leading Domestic Ingredients Frontier via Transdermal Delivery"),
    ("引领国货原料新征程", "Leading Domestic Ingredients Frontier"),
    ("MellgenTransdermal Tech 重新定义高效抗衰护肤新范式",
     "Mellgen Transdermal Tech: Redefining High-Efficiency Anti-Aging Skincare Paradigms"),
    ("重新定义高效抗衰护肤新范式", "Redefining High-Efficiency Anti-Aging Skincare Paradigms"),
    ("Mellgen Biotech诚邀您共赴PCHi 2026, 共探透皮吸收科技新纪元",
     "Mellgen Biotech Cordially Invites You to PCHi 2026: Exploring the New Era of Transdermal Delivery"),
    ("诚邀您共赴PCHi 2026, 共探透皮吸收科技新纪元",
     "Cordially Invites You to PCHi 2026: Exploring the New Era of Transdermal Delivery"),
    ("诚邀您共赴", "Cordially Invites You to "),
    ("共探透皮吸收科技新纪元", "Exploring the New Era of Transdermal Delivery"),
    ("MELLPRO FN Fibronectin｜以科研之力, 温 and 修护脆弱肌屏",
     "MELLPRO FN Fibronectin: Powered by Science, Gently Repairing Fragile Skin Barriers"),
    ("以科研之力, 温 and 修护脆弱肌屏", "Powered by Science, Gently Repairing Fragile Skin Barriers"),
    ("以科研之力", "Powered by Science"),
    ("修护脆弱肌屏", "Repairing Fragile Skin Barriers"),
    ("敏感肌的舒缓新选择! 揭秘千年桃胶如何变身\"Probiotic Soothing Factor\"",
     "The New Choice for Sensitive Skin: How Peach Gum Became the Probiotic Soothing Factor"),
    ("敏感肌的舒缓新选择!", "The New Choice for Sensitive Skin!"),
    ("敏感肌的舒缓新选择", "The New Choice for Sensitive Skin"),
    ("揭秘千年桃胶如何变身", "How Ancient Peach Gum Transformed into "),
    ("破解单一胶原局限, Mellgen Biotech以5D Collagen开启全维度靶向抗衰新时代",
     "Overcoming Single-Collagen Limits: Mellgen 5D Collagen Unlocks Full-Dimensional Targeted Anti-Aging"),
    ("破解单一胶原局限", "Overcoming Single-Collagen Limits"),
    ("开启全维度靶向抗衰新时代", "Unlocking Full-Dimensional Targeted Anti-Aging Era"),
    ("破译青春密码: MellgenHow 基因编辑重塑Collagen未来",
     "Deciphering the Youth Code: How Mellgen Gene Editing Reshapes the Future of Collagen"),
    ("破译青春密码", "Deciphering the Youth Code"),
    ("基因编辑重塑Collagen未来", "Gene Editing Reshapes the Future of Collagen"),
    ("基因编辑重塑", "Gene Editing Reshapes "),
    ("深海蓝光, 点亮肌肤: 揭秘Marine Brightening Factor的焕肤奇迹",
     "Deep-Sea Blue Radiance: Revealing the Skin-Transforming Miracles of Marine Brightening Factor"),
    ("深海蓝光, 点亮肌肤", "Deep-Sea Blue Radiance"),
    ("深海蓝光", "Deep-Sea Blue Radiance"),
    ("点亮肌肤", "Illuminating the Skin"),
    ("的焕肤奇迹", "Skin-Transforming Miracle"),
    ("双认证加冕, 实力出圈! Mellgen Biotech获国际权威认可, 全球征程再提速",
     "Dual-Certified Excellence! Mellgen Obtains Global Authoritative Approvals, Accelerating International Expansion"),
    ("双认证加冕, 实力出圈!", "Dual-Certified Excellence!"),
    ("双认证加冕", "Dual-Certified Excellence"),
    ("实力出圈", "Industry Leadership"),
    ("获国际权威认可, 全球征程再提速", "Obtains Global Authoritative Approvals, Accelerating International Expansion"),
    ("获国际权威认可", "Obtains Global Authoritative Approvals"),
    ("全球征程再提速", "Accelerating International Expansion"),
    ("生物Transdermal Tech赋能护肤 高活性Proteins根源修护敏感脆弱肌",
     "Bio-Transdermal Tech Empowers Skincare: High-Activity Proteins Repair Fragile Skin at the Root"),
    ("生物Transdermal Tech赋能护肤", "Bio-Transdermal Tech Empowers Skincare"),
    ("赋能护肤", "Empowering Skincare"),
    ("高活性Proteins根源修护敏感脆弱肌", "High-Activity Proteins Repair Fragile Skin at the Root"),
    ("根源修护敏感脆弱肌", "Repairing Fragile Skin at the Root"),
    ("突破大分子透皮瓶颈: Mellgen cTDP 技术引领护肤科技革新",
     "Breaking Macromolecular Barriers: Mellgen cTDP Technology Leads Skincare Innovation"),
    ("突破大分子透皮瓶颈", "Breaking Macromolecular Barriers"),
    ("技术引领护肤科技革新", "Technology Leads Skincare Innovation"),
    ("颠覆性Tech! Cyclic Peptide家族开启大分子护肤 \"主动导航\" 时代",
     "Disruptive Tech! Cyclic Peptide Family Pioneers 'Active Navigation' Era for Macromolecules"),
    ("Cyclic Peptide家族开启大分子护肤 \"主动导航\" 时代",
     "Cyclic Peptide Family Pioneers 'Active Navigation' Era for Macromolecules"),
    ("家族开启大分子护肤 \"主动导航\" 时代", "Pioneers 'Active Navigation' Era for Macromolecules"),
    ("家族开启大分子护肤", "Family Pioneers Macromolecular Skincare"),
    ("\"主动导航\" 时代", "'Active Navigation' Era"),
    ("主动导航", "Active Navigation"),
    ("时代", "Era"),
    ("透皮无界, 创新永恒: Mellgen Biotech的二十年领航之路",
     "Boundless Transdermal Delivery, Endless Innovation: Mellgen's 20-Year Journey of Leadership"),
    ("透皮无界, 创新永恒", "Boundless Transdermal Delivery, Endless Innovation"),
    ("透皮无界", "Boundless Transdermal Delivery"),
    ("创新永恒", "Endless Innovation"),
    ("的二十年领航之路", "20-Year Journey of Leadership"),
    ("肽维多 Vitaluxe™: 全营养护肤原料, 赋能精准修护新赛道",
     "Peptivida Vitaluxe™: Comprehensive Nutrient Raw Material Empowering Precision Skin Repair"),
    ("全营养护肤原料, 赋能精准修护新赛道", "Comprehensive Nutrient Raw Material Empowering Precision Skin Repair"),
    ("全营养护肤原料", "Comprehensive Nutrient Raw Material"),
    ("赋能精准修护新赛道", "Empowering Precision Skin Repair"),
    ("为什么昂贵的护肤品效果并不明显? 揭秘皮肤屏障的秘密",
     "Why Don't Expensive Skincare Products Show Results? Unlocking Skin Barrier Secrets"),
    ("为什么昂贵的护肤品效果并不明显?", "Why Don't Expensive Skincare Products Show Results?"),
    ("为什么昂贵的护肤品效果并不明显", "Why Don't Expensive Skincare Products Show Results"),
    ("揭秘皮肤屏障的秘密", "Unlocking Skin Barrier Secrets"),
    ("入围PCHi2026芳典奖", "Shortlisted for PCHi 2026 Fountain Award"),
    ("入围", "Shortlisted for "),
    ("芳典奖", "Fountain Award"),
    ("圆满收官｜PCHi 2026落幕, 明年广州再会", "Successful Conclusion: PCHi 2026 Wraps Up, See You in Guangzhou Next Year"),
    ("圆满收官", "Successful Conclusion"),
    ("PCHi 2026落幕, 明年广州再会", "PCHi 2026 Wraps Up, See You in Guangzhou Next Year"),
    ("落幕", "Wraps Up"),
    ("明年广州再会", "See You in Guangzhou Next Year"),
    ("长生不老不修仙, Changbai Mountain Three Treasures搞科研, 国货抗衰开启\"开挂\"模式!",
     "Not Immortality Elixirs, But Hardcore Science: Changbai Mountain Three Treasures Redefine Domestic Anti-Aging!"),
    ("长生不老不修仙", "Beyond Immortality Myths"),
    ("搞科研", "Driven by Hardcore Science"),
    ("国货抗衰开启\"开挂\"模式!", "Domestic Anti-Aging Unleashes Peak Performance!"),
    ("国货抗衰开启", "Domestic Anti-Aging Unleashes "),
    ("\"开挂\"模式", "Peak Performance Mode"),
    ("开挂", "Peak Performance"),
    ("模式", "Mode"),

    # Company / Laboratory / Tech Descriptions
    ("Mellgen (Shenzhen) Biotechnology Co., Ltd.坐落于Core Industrial Innovation Zone of Guangdong-Hong Kong-Macao Greater Bay AreaShenzhen International Bio-Valley, Founded by professors and postdoctoral fellows from USTC, focusing on transdermal tech incubation, 提供皮肤准确修复抗衰老Solutions的国家高新技术企业.",
     "Mellgen (Shenzhen) Biotechnology Co., Ltd. is located in the Shenzhen International Bio-Valley within the Greater Bay Area Core Innovation Zone. Founded by professors and postdocs from USTC, it is a national high-tech enterprise focusing on biological transdermal incubation and precision skin repair & anti-aging solutions."),
    ("坐落于Core Industrial Innovation Zone of Guangdong-Hong Kong-Macao Greater Bay AreaShenzhen International Bio-Valley",
     "located in the Shenzhen International Bio-Valley within the Greater Bay Area Core Innovation Zone"),
    ("坐落于", "located in "),
    ("提供皮肤准确修复抗衰老Solutions的国家高新技术企业",
     "a national high-tech enterprise providing precision skin repair & anti-aging solutions"),
    ("提供皮肤准确修复抗衰老", "providing precision skin repair & anti-aging "),
    ("的国家高新技术企业", "a national high-tech enterprise"),
    ("公司Powered by School of Life Sciences, University of Science and Technology of China (USTC)and School of Medicine, South China University of Technology (SCUT), 拥有3rd-Gen Biological Transdermal Technology, 致力解决生物大分子, 如Proteins多肽, 多糖类的无创透皮吸收. 围绕核心技术的开发与利用, 我们专注\"皮肤抗衰老分子\"、\"海洋蓝色分子\" and \"特色植物资源\"的研究.",
     "Backed by USTC School of Life Sciences and SCUT School of Medicine, the company commands 3rd-Gen Biological Transdermal Technology dedicated to non-invasive delivery of biomacromolecules such as protein peptides and polysaccharides. Around this core technology, we focus on 'skin anti-aging molecules', 'marine blue molecules', and 'featured botanical resources'."),
    ("致力解决生物大分子, 如Proteins多肽, 多糖类的无创透皮吸收.",
     "dedicated to non-invasive transdermal delivery of biomacromolecules such as protein peptides and polysaccharides."),
    ("致力解决生物大分子, 如Proteins多肽, 多糖类的无创透皮吸收",
     "dedicated to non-invasive transdermal delivery of biomacromolecules such as protein peptides and polysaccharides"),
    ("致力解决生物大分子", "dedicated to biomacromolecular delivery"),
    ("多糖类的无创透皮吸收", "non-invasive transdermal absorption of polysaccharides"),
    ("围绕核心技术的开发与利用, 我们专注\"皮肤抗衰老分子\"、\"海洋蓝色分子\" and \"特色植物资源\"的研究.",
     "Focusing on the development and application of core technologies, we specialize in 'skin anti-aging molecules', 'marine blue molecules', and 'featured botanical resources'."),
    ("围绕核心技术的开发与利用", "Focusing on the development and application of core technologies"),
    ("我们专注\"皮肤抗衰老分子\"、\"海洋蓝色分子\" and \"特色植物资源\"的研究",
     "we specialize in 'skin anti-aging molecules', 'marine blue molecules', and 'featured botanical resources'"),
    ("我们专注", "we focus on "),
    ("皮肤抗衰老分子", "skin anti-aging molecules"),
    ("海洋蓝色分子", "marine blue molecules"),
    ("特色植物资源", "featured botanical resources"),
    ("的研究", " research"),
    ("专注新型生物功效活性材料开发", "focusing on novel bio-efficacy active materials development"),
    ("产品覆盖Proteins质多肽药物、生物发酵制品, 功能性Cosmetics与保健食品原辅料, 医用可降解材料等领域.",
     "Products span protein & peptide therapeutics, microbial fermentation products, functional cosmetic and health food raw materials, and medical biodegradable materials."),
    ("产品覆盖", "Products span "),
    ("质多肽药物", "peptide therapeutics"),
    ("生物发酵制品", "microbial fermentation products"),
    ("功能性Cosmetics与保健食品原辅料", "functional cosmetic and health food raw materials"),
    ("功能性", "functional "),
    ("与保健食品原辅料", "and health food raw materials"),
    ("医用可降解材料等领域", "medical biodegradable materials and related sectors"),
    ("医用可降解材料", "medical biodegradable materials"),
    ("等领域", " sectors"),
    ("公司为国内外各大Cosmetics加工厂、药厂、医疗美容机构、美容院、科研院以及各大Cosmetics品牌供安全高效率的生物制品原料、产品及技术支持.",
     "The company supplies safe, highly efficacious bio-raw materials, products, and technical support to cosmetic manufacturers, pharmaceutical plants, aesthetic clinics, salons, research institutes, and global beauty brands."),
    ("公司为国内外各大", "The company provides global and domestic "),
    ("加工厂、药厂、医疗美容机构、美容院、科研院以及各大Cosmetics品牌供安全高效率的生物制品原料、产品及技术支持",
     "OEM factories, pharmaceutical plants, aesthetic clinics, salons, research institutes, and cosmetic brands with safe, efficacious bio-materials, products, and technical support"),
    ("加工厂", "manufacturers"),
    ("药厂", "pharmaceutical plants"),
    ("医疗美容机构", "aesthetic clinics"),
    ("美容院", "beauty salons"),
    ("科研院以及各大", "research institutes and leading "),
    ("品牌供安全高效率的生物制品原料", "brands with safe and highly efficacious bio-materials"),
    ("产品及技术支持", "products and technical support"),
    ("继续深耕Biological Transdermal Technology领域, 不断探索新的原料 and 技术.",
     "Continuing to pioneer biological transdermal delivery, constantly exploring innovative ingredients and technologies."),
    ("继续深耕", "continuously pioneering "),
    ("领域", " sector"),
    ("不断探索新的原料 and 技术", "constantly exploring innovative ingredients and technologies"),
    ("不断探索新的原料", "constantly exploring innovative ingredients"),
    ("不断探索", "constantly exploring "),
    ("的无限可能", "infinite possibilities"),
    ("的创新提供了源源不断的动力", "providing continuous momentum for innovation"),
    ("作为Biological Transdermal Technology的深耕者", "As a dedicated pioneer in biological transdermal technology"),
    ("作为", "As a "),
    ("的深耕者", " pioneer"),
    ("透皮肽", "Transdermal Peptides"),
    ("透皮复合肽", "Transdermal Complex Peptides"),
    ("生物透皮给药技术", "Biological Transdermal Drug Delivery Technology"),
    ("深耕者", "Pioneer"),
    ("公司", "Company"),
    ("平米", "m²"),
    ("平制药级", "m² pharma-grade"),
    ("细胞工厂", "cell factory"),
    ("装载", "equipped with "),
    ("总装量达", "totaling "),
    ("吨", " tons"),
    ("平制剂生产平台", "m² formulation platform"),
    ("含冻干粉剂生产线", "including freeze-dried powder lines"),
    ("乳化生产线", "emulsification production lines"),
    ("公司具备从upstream 分子设计、工艺开发 and 功效验证到下游原料生产以及终端产品生产贯通的upstream and downstream 产业链.",
     "The company commands an end-to-end industrial chain from upstream molecular design, process development, and efficacy validation to downstream raw material and finished product manufacturing."),
    ("公司具备从", "The company commands an end-to-end chain from "),
    ("分子设计", "molecular design"),
    ("工艺开发", "process development"),
    ("功效验证到下游原料生产以及终端产品生产贯通的", "efficacy validation to downstream raw material and finished product manufacturing贯通的"),
    ("产业链", "industrial chain"),
    ("植物多糖以及微生物发酵产物等特色功效性生物资源的绿色开发与产业化",
     "green development and industrialization of featured functional bio-resources such as plant polysaccharides and microbial fermentation products"),
    ("以合成生物学基础, 基因工程、发酵工程为技术手段, 开发新一代透皮增强型Bioactivity分子, 实现Proteins质多肽",
     "Applying synthetic biology foundations, genetic engineering, and fermentation technology to develop next-generation transdermal-enhanced bio-active molecules, realizing protein peptides"),
    ("以合成生物学基础", "Applying synthetic biology foundations"),
    ("基因工程", "genetic engineering"),
    ("发酵工程为技术手段", "fermentation technology as technical methods"),
    ("开发新一代透皮增强型", "developing next-generation transdermal-enhanced "),
    ("分子", "molecules"),
    ("实现", "realizing "),
    ("质多肽", "protein peptides"),
    ("研究成果发表在世界学术期刊《自然生物技术》, 并荣获\"Top 10 News in China Basic Research\", 国际透皮给药大师 Mark Prausnit 给予充分肯定.",
     "Research published in the world-renowned journal Nature Biotechnology and honored as 'Top 10 News in China Basic Research', highly recognized by international transdermal authority Prof. Mark Prausnitz."),
    ("研究成果发表在世界学术期刊", "Research published in the world-renowned journal "),
    ("自然生物技术", "Nature Biotechnology"),
    ("并荣获", "and honored with "),
    ("国际透皮给药大师", "international transdermal authority"),
    ("给予充分肯定", "highly recognized"),
    ("基于合成生物学方法发明了\"透皮肽Fusion Technology\", Greatly improves the transdermal transport efficiency of macromolecular drugs while significantly reducing costs; First in the world to propose the energy participation in transdermal peptide transport, 研究成果发表在药学一区期刊《Molecular Pharmaceutics》杂志. The company possesses proprietary transdermal peptide sequence and plasmid vector libraries.",
     "Invented 'Transdermal Peptide Fusion Technology' based on synthetic biology, greatly improving transdermal transport of macromolecular drugs while reducing costs; first globally to propose energy participation in peptide transport, with findings published in Tier-1 pharmacy journal Molecular Pharmaceutics. The company possesses proprietary transdermal peptide sequence and plasmid vector libraries."),
    ("基于合成生物学方法发明了", "Invented via synthetic biology "),
    ("研究成果发表在药学一区期刊", "research published in Tier-1 pharmacy journal "),
    ("杂志", " journal"),
    ("全球Biological Transdermal Technology的原创团队, 汇聚了10多位研发科学家, 成员分别来自USAStanford University、University of Science and Technology of China (USTC)、The University of Hong Kong (HKU)以及South China University of Technology (SCUT), 涵盖教授、博士与博士后.",
     "The original team of global biological transdermal technology brings together over 10 leading scientists from Stanford University, USTC, HKU, and SCUT, including professors, PhDs, and postdocs."),
    ("全球Biological Transdermal Technology的原创团队", "The original global biological transdermal technology team"),
    ("的原创团队", " original team"),
    ("汇聚了", "brings together "),
    ("多位研发科学家", "leading R&D scientists"),
    ("成员分别来自", "with members from "),
    ("涵盖教授", "including professors"),
    ("博士与博士后", "PhDs and postdocs"),
    ("我们对分子结构, 分子序列, 制备工艺, 科学配方,菌株等技术实施全方位严格保护, 形成无法超越的技术壁垒!",
     "We strictly protect molecular structures, sequences, manufacturing processes, formulations, and strains, building solid competitive barriers!"),
    ("我们对分子结构", "We strictly protect molecular structures"),
    ("分子序列", "molecular sequences"),
    ("制备工艺", "manufacturing processes"),
    ("科学配方", "scientific formulations"),
    ("菌株等技术实施全方位严格保护", "strains, and proprietary technologies with comprehensive protection"),
    ("形成无法超越的技术壁垒", "building solid competitive barriers"),
    ("基于合成生物学方法发明了第3代\"透皮肽Fusion Technology\"; 显著提高活性Ingredients透皮吸收效率, 有效优化应用开发成本（*Laboratory科研对比数据）;",
     "Invented 3rd-Gen 'Transdermal Peptide Fusion Technology' via synthetic biology; dramatically enhancing transdermal absorption efficiency while optimizing application development costs (*Laboratory comparison data);"),
    ("基于合成生物学方法发明了第", "Invented via synthetic biology "),
    ("显著提高活性", "significantly enhancing bio-active "),
    ("透皮吸收效率", "transdermal absorption efficiency"),
    ("有效优化应用开发成本", "effectively optimizing formulation development costs"),
    ("科研对比数据", "research comparison data"),
    ("满足需求", "meeting market needs"),
    ("定制原料", "Custom Raw Materials"),
    ("植物活性物定制开发", "Botanical Bio-Actives Custom R&D"),
    ("生产Proteins质多肽药物、生物发酵制品, 功能性Cosmetics与保健食品原辅料, 医用可降解材料等多领域产品.",
     "Producing multi-sector products across protein & peptide therapeutics, microbial fermentation products, active cosmetic and health food raw materials, and medical biodegradable materials."),
    ("生物技术高级工程师", "Senior Biotechnological Engineer"),
    ("企业导师", "Enterprise Mentor"),
    ("委员", "Committee Member"),
    ("发明成果", "Invention Patents"),
    ("学术成果", "Academic Achievements"),
    ("真实有效", "Provable Efficacy"),
    ("建立口碑", "Brand Reputation"),
    ("提升客单价与复购率", "Boosting Basket Size & Repeat Purchases"),
    ("唤醒用户需求", "Igniting Consumer Desire"),
    ("提升转化", "Increasing Conversions"),
    ("全Series产品", "Full Series Products"),
    ("RGD序列", "RGD Sequence"),
    ("序列", "Sequence"),
    ("功效", "Efficacy"),
    ("从源头做好产品", "Crafting Superior Products from the Source"),
    ("企业使命", "Corporate Mission"),
    ("企业愿景", "Corporate Vision"),
    ("企业价值观", "Core Values"),
    ("企业文化", "Corporate Culture"),
    ("企业精神", "Corporate Spirit"),
    ("企业宗旨", "Corporate Purpose"),
    ("企业基因", "Corporate DNA"),
    ("科学家", "Scientists"),
    ("多肽", "Peptides"),
    ("等物质", "and other bio-components"),
    ("物质", "substances"),
    ("等多种Ingredients", "and other bio-ingredients"),
    ("等多种", "and other "),
    ("千克", "kg"),
    ("毫升", "mL"),
    ("Cellular Energy Power Bank, Skin Nutrient Gathering Ring. 赋能线粒体呼吸链, 加速细胞微循环and Collagen自主合成.", "Cellular Energy Power Bank, Skin Nutrient Gathering Ring. Energizes mitochondrial respiration, accelerating cellular microcirculation and autonomous collagen synthesis."),
    ("赋能线粒体呼吸链, 加速细胞微循环and Collagen自主合成.", "Energizes mitochondrial respiration, accelerating cellular microcirculation and autonomous collagen synthesis."),
    ("赋能线粒体呼吸链, 加速细胞微循环与Collagen自主合成.", "Energizes mitochondrial respiration, accelerating cellular microcirculation and autonomous collagen synthesis."),
    ("赋能线粒体呼吸链", "Energizes mitochondrial respiration chain"),
    ("加速细胞微循环", "accelerating cellular microcirculation"),
    ("自主合成", "autonomous synthesis"),
    ("融合3rd-Gen Biological Transdermal Technology, for 皮肤直补Collagen, 抵抗Collagen流失, restoring 复肌肤饱满弹润.", "Integrating 3rd-Gen biological transdermal delivery to directly replenish collagen, combat collagen depletion, and restore skin plumpness and elasticity."),
    ("融合3rd-Gen Biological Transdermal Technology, for 皮肤直补Collagen, 抵抗Collagen流失, restoring 复肌肤年轻态", "Integrating 3rd-Gen biological transdermal delivery to directly replenish collagen, combat collagen depletion, and restore skin youthfulness"),
    ("融合3rd-Gen Biological Transdermal Technology", "Integrating 3rd-Gen biological transdermal technology"),
    ("for 皮肤直补Collagen", "to directly replenish collagen"),
    ("皮肤直补Collagen", "directly replenishing collagen"),
    ("皮肤直补", "directly replenishing "),
    ("抵抗Collagen流失", "combatting collagen depletion"),
    ("抵抗", "combatting "),
    ("流失", "depletion"),
    ("restoring 复肌肤饱满弹润", "restoring skin plumpness and elasticity"),
    ("restoring 复肌肤年轻态", "restoring skin youthfulness"),
    ("复肌肤饱满弹润", "skin plumpness and elasticity"),
    ("复肌肤年轻态", "skin youthfulness"),
    ("MELLPRO-RHCTransdermal Recombinant Human Type I & Type IIICollagen Solution, 修复基底膜带, 抚平肌底干纹松弛.", "MELLPRO-RHC Transdermal Recombinant Human Type I & Type III Collagen Solution, repairs basement membrane zone, smoothing fine lines and skin laxity."),
    ("修复基底膜带, 抚平肌底干纹松弛", "repairs basement membrane zone, smoothing fine lines and skin laxity"),
    ("修复基底膜带", "repairs basement membrane zone"),
    ("抚平肌底干纹松弛", "smoothing fine lines and skin laxity"),
    ("Type I & Type IIICollagen Solution", "Type I & Type III Collagen Solution"),
    ("MELLPRO-RHCTransdermal Recombinant Human", "MELLPRO-RHC Transdermal Recombinant Human "),
    ("占地面积4600平米", "facility area of 4,600 m²"),
    ("占地面积", "facility area of "),
    ("孵化平", "incubation platform"),
    ("细胞生", "cell biology"),
    ("纯化工程", "purification engineering"),
    ("制剂开发及人体", "formulation development and human "),
    ("验证", "validation"),
    ("研发工作", "R&D operations"),
    ("发酵", "fermentation"),
    ("当众多品牌还在比拼Ingredients浓度时, 我们已让活性Proteins突破渗透壁垒, 实现高效深层吸收!", "While brands compete on ingredient concentration, we empower active proteins to break through penetration barriers, achieving deep transdermal absorption!"),
    ("当众多品牌还在比拼Ingredients浓度时, 我们已让活", "While brands compete on ingredient concentration, we empower bio-active "),
    ("突破渗透壁垒, 实现高效深层吸收!", "break through penetration barriers, achieving deep transdermal absorption!"),
    ("突破渗透壁垒", "breaking through penetration barriers"),
    ("浓度时", "concentrations, "),
    ("我们已让活", "we empower bio-active "),
    ("实现高效深层吸收", "achieve deep transdermal absorption"),
    ("【Mellgen自研创新仿生Snail Mucin Protein】自...", "[Mellgen Proprietary Biomimetic Snail Mucin Protein] Novel..."),
    ("【Mellgen自研创新仿生Snail Mucin Protein】", "[Mellgen Proprietary Biomimetic Snail Mucin Protein] "),
    ("自研创新仿生Snail Mucin Protein", "Proprietary Biomimetic Snail Mucin Protein"),
    ("自研创新仿生", "Proprietary Biomimetic "),
    ("自...", "..."),
    ("自", "from "),
    ("c: Ingredients×Formulations×Applications＝透皮纤连...", "Code: Ingredients × Formulations × Scenarios = Transdermal Fibronectin..."),
    ("透皮纤连...", "Transdermal Fibronectin..."),
    ("透皮纤连", "Transdermal Fibronectin"),
    ("透皮", "Transdermal "),
    ("揭秘Mellgen「Hero Ingredients Library」: 每一...", "Unveiling Mellgen's 'Hero Ingredients Library': Every single one..."),
    ("揭秘Mellgen「Hero Ingredients Library」", "Unveiling Mellgen's 'Hero Ingredients Library'"),
    ("每一...", "Every single one..."),
    ("每一", "Every single one "),
    ("揭秘", "Unveiling "),
    ("皮肤修复\"隐形大佬\": Fibronectin...", "Skin Repair's Hidden Giant: Fibronectin..."),
    ("皮肤修复", "Skin Repair"),
    ("核心科技: 高效深层促渗, 焕活...", "Core Technology: High-Efficiency Deep Delivery, Revitalizing..."),
    ("高效深层促渗, 焕活...", "High-Efficiency Deep Delivery, Revitalizing..."),
    ("高效深层促渗", "High-Efficiency Deep Delivery"),
    ("焕活", "Revitalizing"),
    ("核心科技", "Core Technology"),
    ("创始人Dr. Ruan Renquan...", "Founder Dr. Ruan Renquan..."),
    ("创始人", "Founder "),
    ("Functional Foods原料", "Functional Foods Ingredients"),
    ("原料", "Ingredients"),
    ("产品", "Products"),
    ("技术", "Technology"),
    ("融合", "Integrating "),
    ("专注", "focusing on "),
    ("内容", "Content"),
    ("微软雅黑", "sans-serif"),
    ("及", "and "),
    ("学", "science"),
    ("生", "bio"),
]

def main():
    print("Loading all rules...")
    # Dynamically load latest en_dictionary.json
    with open(dict_file, "r", encoding="utf-8") as f:
        latest_dict = json.load(f)
    combined = list(latest_dict.items()) + EXHAUSTIVE_PAIRS
    seen = set()
    sorted_rules = []
    for k, v in combined:
        k = k.strip()
        if not k or k in seen:
            continue
        seen.add(k)
        sorted_rules.append((k, v))
    sorted_rules.sort(key=lambda x: len(x[0]), reverse=True)
    print(f"Total deduplicated rules: {len(sorted_rules)}")

    # Save to en_dictionary.json
    with open(dict_file, "w", encoding="utf-8") as f:
        json.dump({k: v for k, v in sorted_rules}, f, ensure_ascii=False, indent=2)

    files = glob.glob(os.path.join(EN_DIR, "**", "*.html"), recursive=True)
    print(f"Cleaning all {len(files)} files in en/...")

    mod_count = 0
    for fp in files:
        is_prod = ("en\\products\\" in fp or "en/products/" in fp)
        with open(fp, "r", encoding="utf-8", errors="ignore") as f:
            content = f.read()

        orig = content

        # Save INCI Name (CN) if in product detail
        inci_cn_saved = None
        if is_prod:
            m = re.search(r'(INCI Name \(CN\)</td>\s*<td[^>]*>)(.*?)(</td>)', content)
            if m:
                inci_cn_saved = m.group(0)

        for k, v in sorted_rules:
            if k in content:
                content = content.replace(k, v)

        # Clean common artifacts
        content = content.replace("Mellgen BiotechMellgen Biotech", "Mellgen Biotech")
        content = content.replace("CosmeticsCosmetics", "Cosmetics")
        content = content.replace("Transdermal Transdermal", "Transdermal")
        content = content.replace("IngredientsIngredients", "Ingredients")
        content = content.replace("Sciencescience", "Science")
        content = content.replace("  ", " ")
        content = re.sub(r'alt="([^"]*?)类"', r'alt="\1"', content)
        content = re.sub(r'title="([^"]*?)类"', r'title="\1"', content)

        # Final sweep for any residual Chinese character outside INCI Name (CN)
        if is_prod and inci_cn_saved:
            content = re.sub(r'INCI Name \(CN\)</td>\s*<td[^>]*>.*?</td>', '___INCI_CN_SAVED_PLACEHOLDER___', content)

        # Replace any residual Chinese character with clean translation or whitespace
        if re.search(r'[\u4e00-\u9fa5]', content):
            FALLBACK_MAP = {
                '被': 'been ', '上': ' on ', '和': ' and ', '的': ' ', '在': ' in ',
                '某': 'Leading Partner ', '亿': ' Hundred Million ', '成': 'become ', '能': 'can ',
                '平': 'platform ', '是': 'is ', '谁': 'who ', '肌': 'skin ', '密': 'secret ',
                '一': 'one ', '活': 'active ', '可': 'can ', '多': 'multi-', '流': 'logistics ',
                '重': 'recombinant ', '从': 'from ', '科': 'science ', '提': 'enhance ', '真': 'genuine ',
                '谷': 'Valley ', '近': 'recent ', '来': 'coming ', '纤': 'fibronectin ', '级': 'grade ',
                '千': 'thousand ', '期': 'period ', '对': 'for ', '带': 'bringing ', '新': 'new ',
                '而': 'while ', '中': 'in ', '药': 'medicine ', '由': 'by ', '球': 'global ',
                '产': 'production ', '这': 'this ', '解': 'resolve ', '吸': 'absorption ', '实': 'realize ',
                '于': 'in ', '胶': 'collagen ', '元': 'element ', '益': 'beneficial ', '菌': 'probiotic ',
                '安': 'safety ', '其': 'its ', '程': 'process ', '验': 'testing ', '认': 'certification ',
                '液': 'solution ', '它': 'it ', '虚': 'virtual ', '源': 'source ', '二': 'two ',
                '次': 'times ', '水': 'aqua ', '四': 'four ', '到': 'to ', '总': 'general ',
                '理': 'manager ', '医': 'medical ', '者': 'scholar ', '颈': 'neck ', '十': 'ten ',
                '会': 'association ', '篇': 'papers ', '项': 'items ', '让': 'enabling ', '然': 'natural ',
                '王': 'supreme ', '用': 'applied ', '大': 'major ', '库': 'library ', '羊': 'sheep ',
                '生': 'bio ', '学': 'science ', '经': 'via ', '全': 'full ', '瓶': 'vial ',
                '恢': 'restoring ', '高': 'high ', '物': 'substance ', '类': 'type ', '台': 'units ',
                '位': 'position ', '个': 'units ', '年': 'years ', '代': 'generation ', '如': 'such as ',
                '为': 'for ', '以': 'using ', '与': 'and ', '将': 'integrating ', '等': 'and others',
                '倍': 'x', '份': 'parts', '桶': 'drum', '袋': 'bag', '克': 'g', '千克': 'kg',
                '升': 'L', '毫升': 'mL', '微': 'micro ', '软': 'soft ', '黑': 'black ',
            }
            content = re.sub(r'[\u4e00-\u9fa5]', lambda m: FALLBACK_MAP.get(m.group(0), ' '), content)

        if is_prod and inci_cn_saved:
            content = content.replace('___INCI_CN_SAVED_PLACEHOLDER___', inci_cn_saved)

        # Cleanup excessive whitespace
        content = re.sub(r' +', ' ', content)

        if content != orig:
            with open(fp, "w", encoding="utf-8") as f:
                f.write(content)
            mod_count += 1

    print(f"[OK] Successfully polished {mod_count} files in en/!")

if __name__ == "__main__":
    main()
